version: '3'

services:
  backend:
    build:
      context: ./docker
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend/:/usr/app
      - /backend/node_modules
    command: sh -c "yarn ${ENV}"
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./docker
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend/:/usr/app
      - /frontend/node_modules
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "3305:3306"
    security_opt:
      - seccomp:unconfined

  test-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${TEST_DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${TEST_DB_ROOTPASS}
      MYSQL_USER: ${TEST_DB_USERNAME}
      MYSQL_PASSWORD: ${TEST_DB_PASS}
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./test-db/data:/var/lib/mysql
    ports:
      - "3307:3306"
    security_opt:
      - seccomp:unconfined

  redis:
    image: redis:latest
    ports:
      - 6379:6379